version: '3.8'

networks:
  intent_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${LOCAL_SUBNET}

services:
  intent-api:
    env_file:
      - .local.env
    build:
      context: .
      dockerfile: local.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      intent_network:
        ipv4_address: ${SERVICE_ADDR}

  db:
    image: postgres:14
    env_file:
      - .local.env 
    environment:
      POSTGRES_DB: ${PSQL_DB_DATABASE_NAME}
      POSTGRES_USER: ${PSQL_DB_USERNAME}
      POSTGRES_PASSWORD: ${PSQL_DB_PASSWORD}
    ports:
      - "${PSQL_DB_PORT}:${PSQL_DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      intent_network:
        ipv4_address: ${PSQL_DB_HOST}

volumes:
  postgres_data:
