name: Deploy FastAPI App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Copy files to server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          TARGET_DIR: /home/${{ secrets.SERVER_USER }}/intent_expert_coherence_api
        run: |
          sshpass -p "$SERVER_PASSWORD" scp -o StrictHostKeyChecking=no -r ./src "$SERVER_USER@$SERVER_IP:$TARGET_DIR"
          sshpass -p "$SERVER_PASSWORD" scp -o StrictHostKeyChecking=no ./Dockerfile "$SERVER_USER@$SERVER_IP:$TARGET_DIR"
          sshpass -p "$SERVER_PASSWORD" scp -o StrictHostKeyChecking=no ./docker-compose.yml "$SERVER_USER@$SERVER_IP:$TARGET_DIR"

      - name: Restart Docker containers
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" << 'ENDSSH'
          cd /home/${{ secrets.SERVER_USER }}/intent_expert_coherence_api
          docker-compose down
          docker-compose up -d --build
          ENDSSH
