name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r test.requirements.txt

    - name: Create .env file
      run: |
        echo "PSQL_DB_USERNAME=${{ secrets.PSQL_DB_USERNAME }}" >> .env
        echo "PSQL_DB_PASSWORD=${{ secrets.PSQL_DB_PASSWORD }}" >> .env
        echo "PSQL_DB_HOST=${{ secrets.PSQL_DB_HOST }}" >> .env
        echo "PSQL_DB_PORT=${{ secrets.PSQL_DB_PORT }}" >> .env
        echo "PSQL_DB_DATABASE_NAME=${{ secrets.PSQL_DB_DATABASE_NAME }}" >> .env

    - name: Run tests
      run: |
        pytest tests/test_api_entity.py
